from io import BytesIO


def test_convert_download_markdown_to_docx(client, headers):
    response = client.post(
        "/v1/convert/download",
        headers=headers,
        data={"tool_name": "md_to_word", "output_filename": "demo.docx"},
        files={"file": ("demo.md", BytesIO(b"# Title\n\n- one\n- two"), "text/markdown")},
    )

    assert response.status_code == 200
    assert response.headers["content-type"].startswith(
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
    )
    assert response.content[:2] == b"PK"


def test_convert_download_markdown_to_pdf(client, headers):
    response = client.post(
        "/v1/convert/download",
        headers=headers,
        data={"tool_name": "md_to_pdf", "output_filename": "demo.pdf"},
        files={"file": ("demo.md", BytesIO(b"# Title\n\nGenerated by tests."), "text/markdown")},
    )

    assert response.status_code == 200
    assert response.headers["content-type"].startswith("application/pdf")
    assert response.content[:4] == b"%PDF"


def test_convert_download_unknown_tool(client, headers):
    response = client.post(
        "/v1/convert/download",
        headers=headers,
        data={"tool_name": "missing_tool"},
        files={"file": ("demo.md", BytesIO(b"# Title"), "text/markdown")},
    )

    assert response.status_code == 404
    assert response.json()["detail"]["code"] == "tool_not_found"


def test_convert_download_requires_file_result(client, headers):
    response = client.post(
        "/v1/convert/download",
        headers=headers,
        data={
            "tool_name": "json_yaml_format",
            "extra_input": '{"text":"{\\"b\\":1,\\"a\\":2}","format":"json"}',
        },
        files={"file": ("demo.json", BytesIO(b'{"b":1,"a":2}'), "application/json")},
    )

    assert response.status_code == 422
    assert response.json()["detail"]["code"] == "tool_did_not_return_file"


def test_convert_download_rejects_invalid_extra_input(client, headers):
    response = client.post(
        "/v1/convert/download",
        headers=headers,
        data={"tool_name": "md_to_word", "extra_input": "{not-json"},
        files={"file": ("demo.md", BytesIO(b"# Title"), "text/markdown")},
    )

    assert response.status_code == 422
    assert response.json()["detail"]["code"] == "invalid_extra_input"


def test_convert_download_requires_api_key(client):
    response = client.post(
        "/v1/convert/download",
        data={"tool_name": "md_to_word"},
        files={"file": ("demo.md", BytesIO(b"# Title"), "text/markdown")},
    )

    assert response.status_code == 401
