from io import BytesIO


def test_upload_and_metadata(client, headers):
    response = client.post(
        "/v1/files",
        headers=headers,
        files={"file": ("hello.md", BytesIO(b"# Hello"), "text/markdown")},
    )
    assert response.status_code == 200
    file_id = response.json()["file_id"]

    metadata = client.post("/v1/tools/file_metadata/run", headers=headers, json={"input": {"file_id": file_id}})
    assert metadata.status_code == 200
    assert metadata.json()["result"]["data"]["filename"] == "hello.md"


def test_markdown_to_docx_sync_fallback(client, headers):
    response = client.post(
        "/v1/tools/md_to_word/run",
        headers=headers,
        json={"input": {"markdown_text": "# Title\n\n- one\n- two", "output_filename": "demo.docx"}},
    )
    assert response.status_code == 200
    result = response.json()["result"]
    assert result["result_file_id"].endswith(".docx")

    download = client.get(f"/v1/files/{result['result_file_id']}", headers=headers)
    assert download.status_code == 200
    assert download.content[:2] == b"PK"


def test_markdown_to_pdf_sync_fallback(client, headers):
    response = client.post(
        "/v1/tools/md_to_pdf/run",
        headers=headers,
        json={"input": {"markdown_text": "# Title\n\nGenerated by tests.", "output_filename": "demo.pdf"}},
    )
    assert response.status_code == 200
    result = response.json()["result"]
    assert result["result_file_id"].endswith(".pdf")

    download = client.get(f"/v1/files/{result['result_file_id']}", headers=headers)
    assert download.status_code == 200
    assert download.content[:4] == b"%PDF"


def test_text_extract_from_markdown(client, headers):
    upload = client.post(
        "/v1/files",
        headers=headers,
        files={"file": ("note.md", BytesIO(b"hello agent"), "text/markdown")},
    )
    file_id = upload.json()["file_id"]
    response = client.post("/v1/tools/text_extract/run", headers=headers, json={"input": {"file_id": file_id}})
    assert response.status_code == 200
    assert response.json()["result"]["data"]["text"] == "hello agent"
